### ISSUE TITLE
Add/Investigate how to provide support for items/equipment added by other mods

### ISSUE THREAD

**Issue by szymonj99** [szymonj99/StartingItemsGUI#19]
I've not looked into this much yet.

I wonder if modded items can just be iterated over using the ItemCatalogue or if we need to provide specific soft dependencies using R2API :thinking:

**Comment by MGJerry** [comment]
From what I've seen so far, modded items from most mods have behave similar to vanilla items (cost, modes, singleplayer and multiplayer)
 
![vanilla_and_modded](https://user-images.githubusercontent.com/85227828/163100447-0f180c6d-efa7-4a6d-b415-46f1eb2145c8.PNG)

**Comment by szymonj99** [comment]
That's awesome, thanks :]

I don't know enough about this so thanks for reaching out.
I'll close this for now as it seems like there are no obvious issues that I can see, and we could re-open this issue if any problems arise in the future. :100:
